analyzer:
  errors:
    constant_identifier_names: ignore
    must_be_immutable: ignore
    prefer_typing_uninitialized_variables: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    
