// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsChBk8QJZPPNMgr_k9fuxPEogqLXtDA0',
    appId: '1:883573169106:web:e333e530119d71f981c60b',
    messagingSenderId: '883573169106',
    projectId: 'lotterie-de-l-etat-haitien',
    authDomain: 'lotterie-de-l-etat-haitien.firebaseapp.com',
    storageBucket: 'lotterie-de-l-etat-haitien.firebasestorage.app',
    measurementId: 'G-N56EK36JQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA913X2NkZJy9DiKjrW0RAJhvaAZsT2-8',
    appId: '1:883573169106:android:f518f80f9960021a81c60b',
    messagingSenderId: '883573169106',
    projectId: 'lotterie-de-l-etat-haitien',
    storageBucket: 'lotterie-de-l-etat-haitien.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1p2yTA05-7eMA5-Xly-L_g3tjWJTBx4M',
    appId: '1:883573169106:ios:7f072e0f14c38e5581c60b',
    messagingSenderId: '883573169106',
    projectId: 'lotterie-de-l-etat-haitien',
    storageBucket: 'lotterie-de-l-etat-haitien.firebasestorage.app',
    iosBundleId: 'com.vision.ayiti-lotri',
  );

}