/// Flutter icons Kiwoo
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Kiwoo
///      fonts:
///       - asset: fonts/Kiwoo.ttf
///
/// 
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class Kiwoo {
  Kiwoo._();

  static const _kFontFam = 'Kiwoo';
  static const String? _kFontPkg = null;

  static const IconData chat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan_market = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning_empty = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_right_bold = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_open = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_rece_money = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_out = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payments = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_in = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData market_address = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData head_phone = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loans_bag = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan_given = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData request_loan = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData received_request = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan_received = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan_request = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_square = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sheild_done_outline = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_circled_alt = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_on = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_location = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_outline = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circled = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData businessman = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_square_outline = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData income = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData businessman_outline = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_location_outline = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_location = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kyc = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sheild_done = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_check = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mc_button_en = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moncash = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mc_button_en2 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData game_roulette = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData win = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData win_filled = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_outline = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tchala = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exchange = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mtn_momo = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circled_outline = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xf002, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xf023, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xf030, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xf03e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData times_circle = IconData(0xf057, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xf058, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_alt = IconData(0xf073, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xf09d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_right = IconData(0xf105, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_down = IconData(0xf107, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xf185, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xf186, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_times = IconData(0xf235, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_card = IconData(0xf2bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xf38c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xf3a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_edit = IconData(0xf4ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
