// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh2liBlSOydjVIpZSvDTcd2Xx3dwDNM64',
    appId: '1:49564633649:web:aa4b38ccdadc014e452310',
    messagingSenderId: '49564633649',
    projectId: 'kiwoo-4597a',
    authDomain: 'kiwoo-4597a.firebaseapp.com',
    storageBucket: 'kiwoo-4597a.firebasestorage.app',
    measurementId: 'G-SPS3HCPH7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGwf0s7BCp55KyYEeMd8AqEX7FE_57hVo',
    appId: '1:49564633649:android:d9af8912fb982851452310',
    messagingSenderId: '49564633649',
    projectId: 'kiwoo-4597a',
    storageBucket: 'kiwoo-4597a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRB3-3ST3twQs3Xf0Ynl6fteniivMOFI8',
    appId: '1:49564633649:ios:294b875f9e384870452310',
    messagingSenderId: '49564633649',
    projectId: 'kiwoo-4597a',
    storageBucket: 'kiwoo-4597a.firebasestorage.app',
    iosBundleId: 'com.vision.kiwoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRB3-3ST3twQs3Xf0Ynl6fteniivMOFI8',
    appId: '1:49564633649:ios:60cf552d3e639e4a452310',
    messagingSenderId: '49564633649',
    projectId: 'kiwoo-4597a',
    storageBucket: 'kiwoo-4597a.firebasestorage.app',
    iosBundleId: 'com.visionMIS.kiwoo.frontEndNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh2liBlSOydjVIpZSvDTcd2Xx3dwDNM64',
    appId: '1:49564633649:web:4eda07211581bf44452310',
    messagingSenderId: '49564633649',
    projectId: 'kiwoo-4597a',
    authDomain: 'kiwoo-4597a.firebaseapp.com',
    storageBucket: 'kiwoo-4597a.firebasestorage.app',
    measurementId: 'G-G01KBJRJSS',
  );
}
